# Generated by Django 5.2 on 2025-05-20 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0004_booking_payment_id_booking_provider_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='images',
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turf_app.turf')),
            ],
        ),
    ]
